Update test_macgputils.yml

diff --git a/.github/workflows/test_macgputils.yml b/.github/workflows/test_macgputils.yml
--- a/.github/workflows/test_macgputils.yml
+++ b/.github/workflows/test_macgputils.yml
@@ -22,9 +22,9 @@ jobs:
       - name: Run powermetrics to check GPU stats
         run: |
           echo "Running powermetrics to check GPU stats"
-          sudo timeout 60s powermetrics --samplers gpu_power > powermetrics_output.txt || echo "Timeout or failure"
+          sudo powermetrics --samplers gpu_power > powermetrics_output.txt || echo "Timeout or failure"
           cat powermetrics_output.txt  # Display the output in the log
 
       - name: Run macgputils_test.py with sudo
         run: |
-          sudo python3 eg.py
+          sudo python3 eg.py  # Run the Python test script with sudo
