Update test_macgputils.yml

diff --git a/.github/workflows/test_macgputils.yml b/.github/workflows/test_macgputils.yml
--- a/.github/workflows/test_macgputils.yml
+++ b/.github/workflows/test_macgputils.yml
@@ -22,8 +22,18 @@ jobs:
       - name: Run powermetrics to check GPU stats
         run: |
           echo "Running powermetrics to check GPU stats"
-          sudo powermetrics --samplers gpu_power > powermetrics_output.txt || echo "Timeout or failure"
+          # Increase timeout to 5 minutes (300s)
+          sudo timeout 300s powermetrics --samplers gpu_power > powermetrics_output.txt || echo "Timeout or failure"
           cat powermetrics_output.txt  # Display the output in the log
+
+      - name: Check if powermetrics worked correctly
+        run: |
+          echo "Checking the powermetrics output for errors"
+          if [[ -s powermetrics_output.txt ]]; then
+            echo "powermetrics output available"
+          else
+            echo "No output from powermetrics. Something went wrong."
+          fi
 
       - name: Run macgputils_test.py with sudo
         run: |
